import {calculate} from './model.mjs';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let d,baseline,res,tab='overview',year=0,outputs=new Map(),nextOut=0;
const tabs=[['overview','Overview'],['waste','Waste and gate fees'],['products','Products and prices'],['equipment','Equipment and investment'],['costs','Costs and staffing'],['settings','Assumptions and ramp-up'],['monthly','Monthly Budget'],['checks','Checks and sources']];
const number=(v,dec=0)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:dec}).format(v||0);
const money=v=>res.fx>0?new Intl.NumberFormat('en-US',{style:'currency',currency:d.settings[6],maximumFractionDigits:0}).format(v/res.fx):'Enter FX rate';
const percent=v=>number(v*100,1)+'%';
function output(fn,type='money'){const id='o'+nextOut++;outputs.set(id,{fn,type});return `<span id="${id}"></span>`;}
function table(head,rows){return `<div class="table-wrap"><table><thead><tr>${head.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;}
const td=(s,cls='')=>`<td class="${cls}">${s}</td>`;
function field(path,value,label,opts={}){const scale=opts.percent?100:1,type=opts.type||'number',attrs=`data-path="${path}" data-scale="${scale}" aria-label="${esc(label)}"`;
 if(opts.options)return `<select ${attrs}>${opts.options.map(v=>`<option ${v===value?'selected':''}>${esc(v)}</option>`).join('')}</select>`;
 return `<input ${attrs} type="${type}" value="${esc(value===null?'':type==='number'?Number((value*scale).toFixed(6)):value)}" ${type==='number'?`min="${opts.min??0}" ${opts.max!==undefined?`max="${opts.max}"`:''} step="${opts.step??'any'}"`:''} ${opts.required?'required':''} ${value===null?'placeholder="To complete"':''}>`;
}
function kpis(){const y=res.years[0];$('kpis').innerHTML=[['Revenue · Year 1',y.revenue,'Product sales + waste gate fees'],['EBITDA · Year 1',y.ebitda,`Share of revenue: ${percent(y.margin)}`],['Initial investment',res.capex,`${number(d.settings[5])} machines + equipment and contingency`],['Additional funding required',res.gap,'Peak cash shortfall over 48 months']].map(([l,v,n])=>`<article class="kpi"><p>${l}</p><strong class="${v<0?'neg':''}">${money(v)}</strong><small>${n}</small></article>`).join('');}
function refresh(){res=calculate(d);kpis();const errors=res.errors; $('alerts').innerHTML=errors.length?`<div class="notice error">${errors.map(esc).join(' ')}</div>`:d.settings[32]!=='Yes'?'<div class="notice">Baseline assumptions require review: 1.2 t/hour per machine and a 50% plastic / 50% construction-residue mix. All inputs are editable.</div>':'';
 for(const [id,{fn,type}] of outputs){const el=$(id);if(!el)continue;const val=fn();el.textContent=type==='money'?money(val):type==='percent'?percent(val):type==='text'?String(val):number(val,type==='decimal'?1:0);el.classList.toggle('neg',typeof val==='number'&&val<0)}
 if($('chart'))$('chart').innerHTML=chart();
 if($('check-list'))$('check-list').innerHTML=checks();
}
function chart(){if(!(res.fx>0))return '<p class="empty">Enter an exchange rate to display the chart in the selected currency.</p>';const all=res.years.flatMap(y=>[y.revenue,y.opex,y.ebitda]).map(v=>v/res.fx),hi=Math.max(...all,1),lo=Math.min(...all,0),height=210,scale=height/(hi-lo),base=35+hi*scale;
 let svg=`<svg class="chart" viewBox="0 0 720 310" role="img" aria-label="Revenue, operating costs and EBITDA over four budget years"><line x1="55" y1="${base}" x2="690" y2="${base}" stroke="#adbbb5"/>`;
 for(let j=0;j<4;j++){const v=lo+(hi-lo)*j/3,y=35+(hi-v)*scale;svg+=`<line x1="55" x2="690" y1="${y}" y2="${y}" stroke="#e5ebe7"/><text x="48" y="${y+5}" text-anchor="end" font-size="13" fill="#63776a">${number(v/1000000,1)}m</text>`;}
 res.years.forEach((y,i)=>{['revenue','opex','ebitda'].forEach((key,j)=>{const val=y[key]/res.fx,h=Math.abs(val)*scale,x=100+i*155+j*28;svg+=`<rect x="${x}" y="${val>=0?base-h:base}" width="22" height="${h}" rx="2" fill="${['#146b4e','#9cafaa','#dfb246'][j]}"><title>Year ${i+1}: ${money(y[key])}</title></rect>`});svg+=`<text x="${128+i*155}" y="282" font-size="15" text-anchor="middle" fill="#355b4c">Year ${i+1}</text>`});return svg+'</svg>';}
const annualRows=[['Waste volume · tonnes','waste','number'],['Product sales','sales'],['Gate fees','gates'],['Total revenue','revenue'],['Waste purchase and handling','raw'],['Binder','binder'],['Electricity','electricity'],['Other variable costs','other'],['Fixed costs and payroll','overhead'],['Total operating costs','opex'],['EBITDA','ebitda'],['EBITDA margin','margin','percent'],['Depreciation','dep'],['Profit before tax','beforeTax'],['Planning tax','tax'],['Profit after planning tax','profit'],['Operating cash flow','operatingCash'],['Equipment and contingency investment','investment'],['Equity contribution','equity'],['Cash at year-end','cash'],['Funding required to year-end','gap']];
function overview(){return `<div class="split"><article class="card"><h3>Revenue and costs over time</h3><div class="legend"><span><i style="background:#146b4e"></i>Revenue</span><span><i style="background:#9cafaa"></i>Operating costs</span><span><i style="background:#dfb246"></i>EBITDA</span></div><div id="chart"></div></article><article class="card"><h3>A steady operating month</h3><div class="summary-strip" style="grid-template-columns:1fr"><div><span>Tonnes of waste processed</span><strong>${output(()=>res.steadyTons,'number')}</strong></div><div><span>Product sales revenue</span><strong>${output(()=>res.steadyTons*d.settings[15]*res.productPrice)}</strong></div><div><span>Gate-fee revenue</span><strong>${output(()=>res.steadyTons*res.gate)}</strong></div></div><p class="fine">Before ramp-up and annual escalation. A steady month uses the selected utilization rate.</p></article></div>${table(['Metric','Year 1','Year 2','Year 3','Year 4'],annualRows.map(([l,k,t])=>`<tr class="${['revenue','opex','ebitda','profit','cash','gap'].includes(k)?'totals':''}">${td(l)}${res.years.map((_,i)=>td(output(()=>res.years[i][k],t),'num')).join('')}</tr>`))}`;}
function waste(){return `<p class="fine">Gate fees are revenue. Payments for waste belong in purchase cost. The waste mix is measured by weight and must total 100%.</p>${table(['Waste type','Mix %','Gate fee ILS/t','Purchase ILS/t','Handling and transport ILS/t','Steady-month tonnes','Gate-fee revenue'],d.waste.map((r,i)=>`<tr>${td(field(`waste.${i}.0`,r[0],'Waste type',{type:'text'}))}${[1,2,3,4].map(k=>td(field(`waste.${i}.${k}`,r[k],`${r[0]} — ${['','Mix','Gate fees','Purchase cost','Handling and transport'][k]}`,{percent:k===1,max:k===1?100:1e9}))).join('')}${td(output(()=>res.steadyTons*d.waste[i][1],'number'),'num')}${td(output(()=>res.steadyTons*d.waste[i][1]*d.waste[i][2]),'num')}</tr>`).concat(`<tr class="totals">${td('Total')}${td(output(()=>res.wasteMix,'percent'))}${td('')}${td('')}${td('')}${td(output(()=>res.steadyTons*res.wasteMix,'number'),'num')}${td(output(()=>res.steadyTons*res.gate),'num')}</tr>`))}<div class="card" style="margin-top:20px"><h3>Baseline price notes</h3>${d.waste.map(r=>`<p class="fine"><b>${esc(r[0])}:</b> ${esc(r[5])}</p>`).join('')}</div>`;}
function products(){return `<p class="fine">Enter selling prices in ILS per tonne. Product mix is by output weight; revenue is shown in the selected currency.</p>${table(['Product','Mix share %','Price ILS/t','Steady-month tonnes','Steady-month revenue','Source / note'],d.products.map((r,i)=>`<tr>${td(field(`products.${i}.0`,r[0],'Product name',{type:'text'}))}${td(field(`products.${i}.1`,r[1],r[0]+' — Mix',{percent:true,max:100}))}${td(field(`products.${i}.2`,r[2],r[0]+' — Price'))}${td(output(()=>res.steadyTons*d.settings[15]*d.products[i][1],'number'),'num')}${td(output(()=>res.steadyTons*d.settings[15]*d.products[i][1]*d.products[i][2]),'num')}${td(esc(r[3]),'row-note')}</tr>`).concat(`<tr class="totals">${td('Total')}${td(output(()=>res.productMix,'percent'))}${td('')}${td(output(()=>res.steadyTons*d.settings[15]*res.productMix,'number'),'num')}${td(output(()=>res.steadyTons*d.settings[15]*res.productPrice),'num')}${td('')}</tr>`))}<p class="fine">All output is assumed to be sold in its production month. Product inventory is not modeled.</p>`;}
function equipment(){return `<p class="fine">Equipment quantity = fixed units + machine count divided by machines per unit, rounded up. Set machines per unit to 0 to disable the variable component.</p>${table(['Equipment','Unit price ILS','Fixed units','Machines per unit','Power kW','Load factor %','Calculated quantity','Investment'],d.equipment.map((r,i)=>`<tr>${td(esc(r[0]))}${[1,2,3,4,5].map(k=>td(field(`equipment.${i}.${k}`,r[k],r[0]+' — '+['','Price','Fixed units','Machines per unit','Power','Load'][k],{percent:k===5,max:k===5?100:1e9,step:k===2?1:'any'}))).join('')}${td(output(()=>res.equipment[i].count,'number'),'num')}${td(output(()=>res.equipment[i].capex),'num')}</tr>`))}<div class="card" style="margin-top:20px"><div class="summary-strip"><div><span>Investment incl. contingency</span><strong>${output(()=>res.capex)}</strong></div><div><span>Total power at selected load · kW</span><strong>${output(()=>res.power,'decimal')}</strong></div><div><span>Investment contingency %</span>${field('settings.31',d.settings[31],'Investment contingency',{percent:true,max:100})}</div></div><p class="fine">Equipment is purchased and paid at the start. One auxiliary unit per five machines is a planning assumption to confirm.</p></div>`;}
function costs(){return `<p class="fine">Enter gross salaries; employer on-cost is added automatically. Fixed expenses continue in months without production.</p>${table(['Cost item','Type','Base rate ILS','Cost driver','Fixed quantity','Machines per unit','Steady-state quantity','Steady-month cost'],d.costs.map((r,i)=>`<tr>${td(field(`costs.${i}.0`,r[0],'Cost name',{type:'text'}))}${td(field(`costs.${i}.1`,r[1],r[0]+' Type',{options:['Payroll','Other']}))}${td(field(`costs.${i}.2`,r[2],r[0]+' Rate'))}${td(field(`costs.${i}.3`,r[3],r[0]+' Basis',{options:['Unit','Equipment item','Product tonne','Waste tonne']}))}${td(field(`costs.${i}.4`,r[4],r[0]+' Fixed quantity'))}${td(field(`costs.${i}.5`,r[5],r[0]+' Machines per unit'))}${td(output(()=>res.costs[i].qty,'decimal'),'num')}${td(output(()=>res.costs[i].amount),'num')}</tr>`))}<p class="fine">Unit driver: fixed quantity + machines divided by machines per unit, rounded up. For equipment-item and tonne drivers, both manual quantity fields are ignored.</p>`;}
function settings(){const groups=[['Production and materials',[11,12,13,14,15,16,17,18,19]],['Start date and price escalation',[20,21,22,23,24]],['Depreciation, tax and cash flow',[25,26,27,28,29,30]],['Rates and assumption approval',[9,32]]],pct=[14,19,22,23,24,25,26];
 return groups.map(([title,ids])=>`<article class="card"><h3>${title}</h3><div class="grid-settings">${ids.map(r=>{const [l,u,n]=d.settingLabels[r],opts={percent:pct.includes(r),type:r===9?'text':'number',required:r!==9};if(r===32)opts.options=['No','Yes'];if([12,13,14,21,25,26,27,28].includes(r))opts.max=({12:24,13:31,14:100,21:12,25:100,26:100,27:24,28:24})[r];if([20,21,27,28].includes(r))opts.step=1;if(r===20){opts.min=2000;opts.max=2100}if(r===21)opts.min=1;if([22,23,24].includes(r))opts.min=-99;return `<label>${esc(l)} · ${esc(u)}${field(`settings.${r}`,d.settings[r],l,opts)}<span>${esc(n)}</span></label>`}).join('')}</div></article>`).join('')+`<article class="card"><h3>Monthly ramp-up · percentage of steady utilization</h3><p class="fine">0% means no production. 100% uses the full selected utilization rate. All 48 months are editable.</p><div class="ramp-grid">${d.ramp.map((v,i)=>`<label>Month ${i+1}${field(`ramp.${i}`,v,`Ramp-up Month ${i+1}`,{percent:true,max:100})}</label>`).join('')}</div></article>`;
}
function monthly(){const rs=[['Waste processed · tonnes','waste','number'],['Product sold · tonnes','product','number'],...annualRows.slice(1,-1),['Customer receipts','receipts'],['Supplier payments','payments'],['Payroll payments','wage'],['Trade receivables','ar'],['Trade payables','ap'],['Cumulative funding shortfall','gap']];return `<div class="year-tabs" aria-label="Budget year">${[0,1,2,3].map(y=>`<button data-year="${y}" class="${year===y?'active':''}" aria-pressed="${year===y}">Year ${y+1}</button>`).join('')}</div>${table(['Metric',...res.months.slice(year*12,year*12+12).map(m=>m.date.toLocaleDateString('en-US',{month:'short',year:'2-digit'}))],rs.map(([l,k,t])=>`<tr class="${['revenue','opex','ebitda','cash','gap'].includes(k)?'totals':''}">${td(l.replace('year-end','month-end'))}${Array.from({length:12},(_,i)=>td(output(()=>res.months[year*12+i][k],t),'num')).join('')}</tr>`))}`;}
function checks(){const issues=res.errors.filter(x=>!x.includes('Rate'));const items=[['Waste mix',Math.abs(res.wasteMix-1)<1e-6,percent(res.wasteMix)],['Product mix',Math.abs(res.productMix-1)<1e-6,percent(res.productMix)],['Exchange rate',res.fx>0,res.fx>0?`${number(res.fx,4)} ILS per currency unit`:'Enter exchange rate'],['Input values',issues.length===0,issues.length?issues.join(' '):'No input errors'],['Funding',res.gap===0,res.gap>0?`Additional funding required: ${money(res.gap)}`:'Cash balances are nonnegative'],['Assumptions approved',d.settings[32]==='Yes',d.settings[32]==='Yes'?'Approved in Settings':'Review and approve in Assumptions and ramp-up']];return table(['Check','Status','Details'],items.map(([l,ok,n])=>`<tr>${td(l)}${td(`<span class="pill ${ok?'':'warn'}">${ok?'PASS':'To complete'}</span>`)}${td(esc(n))}</tr>`));}
function checksPanel(){return `<div id="check-list"></div><article class="card" style="margin-top:20px"><h3>Model scope</h3><p>All calculations exclude VAT, loans and interest, grants, inventory and later equipment expansion. Tax is paid in the profit month without loss carryforwards. Depreciation is capped at equipment cost.</p><p>The original budget multiplied throughput by five and then by machine count again. Here throughput per machine is a separate input: 1.2 tonnes/hour, subject to confirmation.</p><p>Planning assumptions are not quotations. A blank price must be completed when its product or waste stream is active.</p></article><details class="card"><summary>Sources and modeling decisions</summary>${table(['Topic','Source','Reference','Model treatment'],d.sources.map(r=>`<tr>${r.map(v=>td(esc(v))).join('')}</tr>`))}</details>`;}
function render(){outputs.clear();nextOut=0;$('nav').innerHTML=tabs.map(([id,l],i)=>`<button data-tab="${id}" class="${tab===id?'active':''}" ${tab===id?'aria-current="page"':''}><span>${String(i+1).padStart(2,'0')}</span><span>${l}</span></button>`).join('');$('panel-title').textContent=tabs.find(t=>t[0]===tab)[1];$('panel-note').textContent=['overview','monthly'].includes(tab)?'Amounts in the selected reporting currency':'Highlighted fields are editable';$('panel').innerHTML=({overview,waste,products,equipment,costs,settings,monthly,checks:checksPanel})[tab]();refresh();}
function bindTop(){for(const [id,key] of [['machines',5],['currency',6],['usd',7],['eur',8]]){$(id).value=d.settings[key]??'';$(id).oninput=e=>{if(!e.target.validity.valid)return;d.settings[key]=key===6?e.target.value:e.target.value===''?null:Number(e.target.value);d.settings[32]='No';refresh();};}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-tab],[data-year]');if(!b)return;if(b.dataset.tab)tab=b.dataset.tab;else year=Number(b.dataset.year);render();});
document.addEventListener('input',e=>{const el=e.target;if(!el.dataset.path)return;if(!el.validity.valid)return;const parts=el.dataset.path.split('.');let obj=d;for(const key of parts.slice(0,-1))obj=obj[key];obj[parts.at(-1)]=el.type==='number'?(el.value===''?null:Number(el.value)/Number(el.dataset.scale)):el.value;if(el.dataset.path!=='settings.32')d.settings[32]='No';refresh();});
document.addEventListener('change',e=>{if(e.target.matches('input')&&!e.target.validity.valid)e.target.reportValidity();});
$('reset').onclick=()=>$('reset-dialog').showModal();$('reset-dialog').addEventListener('close',()=>{if($('reset-dialog').returnValue==='confirm'){d=structuredClone(baseline);res=calculate(d);bindTop();render();}});
try{const response=await fetch(new URL('./data.json',import.meta.url));if(!response.ok)throw new Error();baseline=await response.json();d=structuredClone(baseline);res=calculate(d);bindTop();render();}catch{ $('alerts').innerHTML='<div class="notice error">The budget data could not be loaded. Please refresh the page.</div>';$('panel-title').textContent='Data could not be loaded';}
